=== Dinesh-NPC/web_technology/xml_schema_dtd/students.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (name?, age, department)>
<!ATTLIST student id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT department (#PCDATA)>

=== Dinesh-NPC/web_technology/xml_schema_dtd/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
<student id="q1">
<name>Alice</name>
<age>20</age>
<department>Computer Science</department>
</student>
<student id="q2">
<name>Bob</name>
<age>22</age>
<department>Electronics</department>
</student>
</students>
